project_id = "oktrzxlwaflyirjfjlad"

[functions.translate]
verify_jwt = false

[functions.help-chat]
verify_jwt = false

[functions.notify-creator-join]
verify_jwt = false

[functions.test-push]
verify_jwt = false

[functions.notify-trip]
verify_jwt = false
